import Head from "next/head";
import AboutUs from "../components/AboutUs";
import OurTeam from "../components/OurTeam";

export default function About() {
    return (
        <>
            <Head>
                <title>About Us</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <header className="h-auto">
                <div className="py-24 md:max-w-none">
                <AboutUs />
                <OurTeam />
                </div>
           </header>

        </>
    );
}


