import React from 'react'
import Head from "next/head";
import Image from "next/image";
import axios from 'axios';
// import data from "../public/data.json"
import { ImBin2 } from 'react-icons/im'
import Link from "next/link"

export async function getStaticProps() {

    return {
        props: {
            photos: data
        }
    };

}

export default function cart({ photos }) {
    return (
        <>
            <Head>
                <title>Cart</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div className="h-auto max-w-5xl mx-auto mt-20 md:space-y-8 md:mt-8 md:mb-8">
                <div className="pt-24">
                <h1 className="text-4xl font-medium">My Cart</h1>
                </div>
                
                {photos.map((order) => (
                    <ul className="flex justify-between items-center text-2xl border-b-2 pb-4 border-gray-300">
                        <li className="space-x-4 flex items-center">
                            <img src={order.src} alt={order.name} className="w-28 h-28" />
                            <span className="font-bold">{order.name}</span>
                        </li>
                        <li>
                            <span>{order.price}</span>
                        </li>
                        <li>
                            <Link href=""><a><ImBin2 size="1.5rem" /></a></Link>
                        </li>
                    </ul>
                ))}
                <div className="bg-gray-800 p-14">
                    <ul className="flex justify-between items-center text-white">
                        <li>
                            Total
                        </li>
                        <li className="text-2xl font-bold">
                            shs 300,000
                        </li>
                        <li>
                            <button className="text-2xl font-medium bg-green-600 text-base px-6 py-4 hover:bg-green-800 transition duration-300" type="button">Order</button>
                        </li>
                    </ul>
                </div>
            </div>
        </>
    )
}
