import Head from "next/head";
import ContactSection from "../components/ContactSection"


export default function Contact() {
    return (
        <>
            <Head>
                <title>Contacts</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <header className="h-auto">
                <div className="py-24 md:max-w-none">
                <ContactSection />
                </div>
           </header>
        </>
    );
}



