import React from 'react'
import Head from "next/head";
// import data from "../public/data.json"
import Image from "next/image";
import Link from "next/link";
// import axios from 'axios';
import { ApolloClient, InMemoryCache } from '@apollo/client'
import { GET_ALL_QUERIES } from '.././graphql/queries'



export async function getStaticProps() {
    // const res = await axios.get("https://qraftstore.herokuapp.com/api/qraftstores?populate=*");
    // const photos = await res.data.data;
    const client = new ApolloClient({
        uri: process.env.STRAPI_GRAPHQL_API,
        cache: new InMemoryCache()
    });
    const { data } = await client.query({
        query: GET_ALL_QUERIES
    })

    return {
        props: { photos: data.qraftstores.data }
    }

}

//    format money with commas
function formatMoney(n) {
    return "shs " + (Math.round(n * 100) / 100).toLocaleString();
}

export default function Gallery({ photos }) {
    console.log('photos', photos)

    return (
        <>
            <Head>
                <title>Gallery</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div className="h-auto container mx-auto mt-20 md:space-y-8 md:mt-8 md:mb-8">
                <h1 className="font-black text-center text-sm md:text-2xl">SEE MORE ORIGINAL PAINTINGS FOR SALE</h1>
                <div className="grid md:grid-cols-4 gap-4 sm:grid-cols-3">
                    {photos.map(photo => (
                        <div key={photo.id} className="flex flex-col">
                            <Link href={`gallery/${photo.id}`}>
                                <a>
                                    <Image
                                        alt={photo.attributes.title}
                                        src={`http://localhost:1337/${photo.url}`}
                                        width={photo.width}
                                        height={photo.height}
                                        
                                    />
                                </a>
                            </Link>
                            <div className="flex justify-between px-4 font-semibold">
                                <div className="flex flex-col">
                                    <h2>{photo.attributes.title}</h2>
                                    <span>{photo.attributes.size}</span>
                                </div>
                                <span>{formatMoney(photo.attributes.price)}</span>
                            </div>

                        </div>
                    ))}
                </div>
            </div>
        </>
    )
}

