import Head from 'next/head'
import Hero from "../components/Hero";
import Layout from "../components/Layout";
import Craft from "../components/Craft";
import axios from 'axios'

//fetch data from db
export async function getStaticProps() {
  const res = await axios.get("https://qraftstore.herokuapp.com/qraftstores");
  const photos = await res.data;

  return {
    props: { photos }
  }
}


export default function Home({photos}) {

  return (
      <>
        <Head>
          <title>Home | Qraft Academy</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
          <Layout>
              <Hero />
              <Craft photos={photos}/>
          </Layout>
      </>
  )
}
